//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.UI.Web.App_Start.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.UI.Web.App_Start.Resources.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account dos not exist..
        /// </summary>
        public static string AccountNotExist {
            get {
                return ResourceManager.GetString("AccountNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Successfully..
        /// </summary>
        public static string ActivatedSuccessfuly {
            get {
                return ResourceManager.GetString("ActivatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is more than the current balance..
        /// </summary>
        public static string AmountIsHi {
            get {
                return ResourceManager.GetString("AmountIsHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked Successfully.
        /// </summary>
        public static string BookedSuccessfully {
            get {
                return ResourceManager.GetString("BookedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press enter to post comment.
        /// </summary>
        public static string CommentIns {
            get {
                return ResourceManager.GetString("CommentIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completied Successfully..
        /// </summary>
        public static string CompletiedSuccessfully {
            get {
                return ResourceManager.GetString("CompletiedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account has been Activated successfully..
        /// </summary>
        public static string DeActivatedSuccessfuly {
            get {
                return ResourceManager.GetString("DeActivatedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully..
        /// </summary>
        public static string DeletedSuccessfuly {
            get {
                return ResourceManager.GetString("DeletedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms first..
        /// </summary>
        public static string errAccept {
            get {
                return ResourceManager.GetString("errAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount can not be empty..
        /// </summary>
        public static string errAmount {
            get {
                return ResourceManager.GetString("errAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the booking fee&apos;s..
        /// </summary>
        public static string errBookingFeesEnter {
            get {
                return ResourceManager.GetString("errBookingFeesEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Branch Name is already taken, try another one..
        /// </summary>
        public static string errBranchAlreadyThere {
            get {
                return ResourceManager.GetString("errBranchAlreadyThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name already exist..
        /// </summary>
        public static string errCategoryNameExist {
            get {
                return ResourceManager.GetString("errCategoryNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the closing time..
        /// </summary>
        public static string errCloseTime {
            get {
                return ResourceManager.GetString("errCloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the password..
        /// </summary>
        public static string errCPass {
            get {
                return ResourceManager.GetString("errCPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket description..
        /// </summary>
        public static string errDescription {
            get {
                return ResourceManager.GetString("errDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the e-mail address..
        /// </summary>
        public static string errEmail {
            get {
                return ResourceManager.GetString("errEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket start in arabic..
        /// </summary>
        public static string errFromAr {
            get {
                return ResourceManager.GetString("errFromAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket start in english..
        /// </summary>
        public static string errFromEng {
            get {
                return ResourceManager.GetString("errFromEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add the Item Description..
        /// </summary>
        public static string errItemDescription {
            get {
                return ResourceManager.GetString("errItemDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the Item Discount Amount..
        /// </summary>
        public static string errItemDiscountAmount {
            get {
                return ResourceManager.GetString("errItemDiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the Discount starting quantity..
        /// </summary>
        public static string errItemDiscountFrom {
            get {
                return ResourceManager.GetString("errItemDiscountFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plese set the Item Discount Percentage..
        /// </summary>
        public static string errItemDiscountPercentage {
            get {
                return ResourceManager.GetString("errItemDiscountPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the Discount type..
        /// </summary>
        public static string errItemDiscountSet {
            get {
                return ResourceManager.GetString("errItemDiscountSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the Garntee days..
        /// </summary>
        public static string errItemGarnteeDate {
            get {
                return ResourceManager.GetString("errItemGarnteeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the Item Name..
        /// </summary>
        public static string errItemName {
            get {
                return ResourceManager.GetString("errItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in user name or password..
        /// </summary>
        public static string errLogin {
            get {
                return ResourceManager.GetString("errLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name..
        /// </summary>
        public static string errName {
            get {
                return ResourceManager.GetString("errName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the arabic name..
        /// </summary>
        public static string errNameAr {
            get {
                return ResourceManager.GetString("errNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the english name..
        /// </summary>
        public static string errNameEng {
            get {
                return ResourceManager.GetString("errNameEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name is already exist..
        /// </summary>
        public static string errNameExist {
            get {
                return ResourceManager.GetString("errNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password..
        /// </summary>
        public static string errOldPass {
            get {
                return ResourceManager.GetString("errOldPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add the owner first..
        /// </summary>
        public static string errOwnerSet {
            get {
                return ResourceManager.GetString("errOwnerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the password..
        /// </summary>
        public static string errPass {
            get {
                return ResourceManager.GetString("errPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password did not match..
        /// </summary>
        public static string errPassMatch {
            get {
                return ResourceManager.GetString("errPassMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak Password..
        /// </summary>
        public static string errPassWeak {
            get {
                return ResourceManager.GetString("errPassWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the user phone number..
        /// </summary>
        public static string errPhone {
            get {
                return ResourceManager.GetString("errPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail or Phone is already registerd to a user, please try again..
        /// </summary>
        public static string errPhoneOrEmail {
            get {
                return ResourceManager.GetString("errPhoneOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phon or an e-mail..
        /// </summary>
        public static string errPhoneOrEmailEnter {
            get {
                return ResourceManager.GetString("errPhoneOrEmailEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Add Clinic Admin or Activate hem..
        /// </summary>
        public static string errPleaseAddClinicAdmin {
            get {
                return ResourceManager.GetString("errPleaseAddClinicAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket price..
        /// </summary>
        public static string errPrice {
            get {
                return ResourceManager.GetString("errPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the service price..
        /// </summary>
        public static string errServicePrice {
            get {
                return ResourceManager.GetString("errServicePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set End Time.
        /// </summary>
        public static string errSetEndTime {
            get {
                return ResourceManager.GetString("errSetEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Patient Limit.
        /// </summary>
        public static string errSetPatientLimit {
            get {
                return ResourceManager.GetString("errSetPatientLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Start Time.
        /// </summary>
        public static string errSetStartTime {
            get {
                return ResourceManager.GetString("errSetStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the starting time..
        /// </summary>
        public static string errStartTime {
            get {
                return ResourceManager.GetString("errStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket title..
        /// </summary>
        public static string errTitle {
            get {
                return ResourceManager.GetString("errTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket destination in arabic..
        /// </summary>
        public static string errToAr {
            get {
                return ResourceManager.GetString("errToAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the ticket destination in english..
        /// </summary>
        public static string errToEng {
            get {
                return ResourceManager.GetString("errToEng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the recipient account address..
        /// </summary>
        public static string errToId {
            get {
                return ResourceManager.GetString("errToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name most not be empty..
        /// </summary>
        public static string errUserName {
            get {
                return ResourceManager.GetString("errUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden Successfully.
        /// </summary>
        public static string HiddenSuccessfully {
            get {
                return ResourceManager.GetString("HiddenSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login to be able to comment..
        /// </summary>
        public static string LoginToComment {
            get {
                return ResourceManager.GetString("LoginToComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login to be able to add new post..
        /// </summary>
        public static string LoginToPost {
            get {
                return ResourceManager.GetString("LoginToPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete this Transaction?.
        /// </summary>
        public static string msCompleteThisTransaction {
            get {
                return ResourceManager.GetString("msCompleteThisTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate this Account?.
        /// </summary>
        public static string msgAcivatethisAccount {
            get {
                return ResourceManager.GetString("msgAcivatethisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book This Tiket.
        /// </summary>
        public static string msgBookThisTiket {
            get {
                return ResourceManager.GetString("msgBookThisTiket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De-Activate this account?.
        /// </summary>
        public static string msgDeAcivatethisAccount {
            get {
                return ResourceManager.GetString("msgDeAcivatethisAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete This?.
        /// </summary>
        public static string msgDelete {
            get {
                return ResourceManager.GetString("msgDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide From Clients.
        /// </summary>
        public static string msgHideFromClients {
            get {
                return ResourceManager.GetString("msgHideFromClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset this user password? (He most enter a new password in his first login)..
        /// </summary>
        public static string msgPassReset {
            get {
                return ResourceManager.GetString("msgPassReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore this branch?.
        /// </summary>
        public static string msgRestoreThisBranch {
            get {
                return ResourceManager.GetString("msgRestoreThisBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore This User?.
        /// </summary>
        public static string msgRestoreThisUser {
            get {
                return ResourceManager.GetString("msgRestoreThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve This Clinic?.
        /// </summary>
        public static string msgRetrieveThisClinic {
            get {
                return ResourceManager.GetString("msgRetrieveThisClinic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve This User?.
        /// </summary>
        public static string msgRetrieveThisUser {
            get {
                return ResourceManager.GetString("msgRetrieveThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll-back this Transaction?.
        /// </summary>
        public static string msgRollBackTransaction {
            get {
                return ResourceManager.GetString("msgRollBackTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as default?.
        /// </summary>
        public static string msgSetToDefault {
            get {
                return ResourceManager.GetString("msgSetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Admin Set.
        /// </summary>
        public static string NoAdminSet {
            get {
                return ResourceManager.GetString("NoAdminSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tickets Avilable Right Now.
        /// </summary>
        public static string NoTicketsAvilableRightNow {
            get {
                return ResourceManager.GetString("NoTicketsAvilableRightNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restored Successfully.
        /// </summary>
        public static string RestoredSuccessfully {
            get {
                return ResourceManager.GetString("RestoredSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieved Successfully.
        /// </summary>
        public static string RetrievedSuccessfuly {
            get {
                return ResourceManager.GetString("RetrievedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolled Back Successfully..
        /// </summary>
        public static string RolledBackSuccessfully {
            get {
                return ResourceManager.GetString("RolledBackSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfuly.
        /// </summary>
        public static string SavedSuccessfuly {
            get {
                return ResourceManager.GetString("SavedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Schedueld Successfully..
        /// </summary>
        public static string TransactionSchedueldSuccessfully {
            get {
                return ResourceManager.GetString("TransactionSchedueldSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Successfully.
        /// </summary>
        public static string UpdatedSuccessfuly {
            get {
                return ResourceManager.GetString("UpdatedSuccessfuly", resourceCulture);
            }
        }
    }
}
